[package]
name = "fol"
version = "0.1.0"
authors = ["Trim Bresilla <trim.bresilla@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
syn = "1"
colored = "1"
dyn-clone = "1"
terminal_size = "0.1.16"
lazy_static = "1.4.0"

#TODO: use <weld> for SIMD
