[package]
name = "fol"
version = "0.1.3"
authors = ["Trim Bresilla <trim.bresilla@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
colored = "1"
dyn-clone = "1"
terminal_size = "0.1.16"
lazy_static = "1.4.0"

