use crate::{
    IntrinsicArity, IntrinsicAvailability, IntrinsicCategory, IntrinsicEntry, IntrinsicId,
    IntrinsicLoweringMode, IntrinsicRoadmap, IntrinsicStatus, IntrinsicSurface,
};

const INTRINSICS: &[IntrinsicEntry] = &[
    IntrinsicEntry::new(
        IntrinsicId::new(0),
        "eq",
        &[],
        IntrinsicCategory::Comparison,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Implemented,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::GeneralIr,
        "compare two values for equality",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(1),
        "nq",
        &["ne"],
        IntrinsicCategory::Comparison,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Implemented,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::GeneralIr,
        "compare two values for inequality",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(2),
        "lt",
        &[],
        IntrinsicCategory::Comparison,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Implemented,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::GeneralIr,
        "compare whether the left value is less than the right value",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(3),
        "gt",
        &[],
        IntrinsicCategory::Comparison,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Implemented,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::GeneralIr,
        "compare whether the left value is greater than the right value",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(4),
        "ge",
        &[],
        IntrinsicCategory::Comparison,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Implemented,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::GeneralIr,
        "compare whether the left value is greater than or equal to the right value",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(5),
        "le",
        &[],
        IntrinsicCategory::Comparison,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Implemented,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::GeneralIr,
        "compare whether the left value is less than or equal to the right value",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(6),
        "not",
        &[],
        IntrinsicCategory::Boolean,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Implemented,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::GeneralIr,
        "negate a boolean value",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(7),
        "len",
        &[],
        IntrinsicCategory::Query,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Implemented,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::DedicatedIr,
        "query the length of a supported value",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(8),
        "echo",
        &["print"],
        IntrinsicCategory::Diagnostic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Implemented,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::RuntimeHook,
        "emit a runtime-visible debug value and forward it unchanged",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(9),
        "cast",
        &[],
        IntrinsicCategory::Conversion,
        IntrinsicSurface::OperatorAlias,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Reject,
        "perform an explicit conversion once the V1 conversion contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(10),
        "as",
        &[],
        IntrinsicCategory::Conversion,
        IntrinsicSurface::OperatorAlias,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Reject,
        "perform an explicit conversion once the V1 conversion contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(11),
        "assert",
        &[],
        IntrinsicCategory::Diagnostic,
        IntrinsicSurface::KeywordCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::AtLeast(1),
        IntrinsicLoweringMode::Reject,
        "assert a condition once the V1 assert contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(12),
        "check",
        &[],
        IntrinsicCategory::Recoverable,
        IntrinsicSurface::KeywordCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Implemented,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::DedicatedIr,
        "inspect whether a recoverable routine call failed",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(13),
        "panic",
        &[],
        IntrinsicCategory::Diagnostic,
        IntrinsicSurface::KeywordCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Implemented,
        IntrinsicArity::AtLeast(0),
        IntrinsicLoweringMode::DedicatedIr,
        "abort control flow immediately",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(14),
        "cap",
        &[],
        IntrinsicCategory::Query,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "query container capacity after the shape query contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(15),
        "is_empty",
        &[],
        IntrinsicCategory::Query,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "query emptiness after the shape query contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(16),
        "de_alloc",
        &[],
        IntrinsicCategory::Memory,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V3,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Reject,
        "explicit deallocation once ownership and lifetime semantics exist",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(17),
        "give_back",
        &[],
        IntrinsicCategory::Memory,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V3,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Reject,
        "return ownership once ownership semantics exist",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(18),
        "address_of",
        &[],
        IntrinsicCategory::Pointer,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V3,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Reject,
        "take the address of a value once pointer semantics exist",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(19),
        "pointer_value",
        &[],
        IntrinsicCategory::Pointer,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V3,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Reject,
        "read a pointer target once pointer semantics exist",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(20),
        "borrow_from",
        &[],
        IntrinsicCategory::Pointer,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V3,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Reject,
        "borrow a value once ownership and borrowing semantics exist",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(21),
        "low",
        &[],
        IntrinsicCategory::Query,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "query the lowest valid index or bound once the range/query contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(22),
        "high",
        &[],
        IntrinsicCategory::Query,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "query the highest valid index or bound once the range/query contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(23),
        "min",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "compute the minimum of two values once the arithmetic intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(24),
        "max",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "compute the maximum of two values once the arithmetic intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(25),
        "clamp",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(3),
        IntrinsicLoweringMode::Deferred,
        "constrain a value to an inclusive range once the arithmetic intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(26),
        "add",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "add two numeric values once the arithmetic intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(27),
        "sub",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "subtract two numeric values once the arithmetic intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(28),
        "mul",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "multiply two numeric values once the arithmetic intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(29),
        "div",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "divide two numeric values once the arithmetic intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(30),
        "abs",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "compute an absolute value once the arithmetic intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(31),
        "floor",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "round a numeric value down once the numeric helper contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(32),
        "ceil",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "round a numeric value up once the numeric helper contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(33),
        "round",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "round a numeric value once the numeric helper contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(34),
        "trunc",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "truncate a numeric value once the numeric helper contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(35),
        "pow",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "raise a value to a power once the arithmetic intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(36),
        "sqrt",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "compute a square root once the numeric helper contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(37),
        "bit_and",
        &[],
        IntrinsicCategory::Bitwise,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "compute a bitwise and once the bitwise intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(38),
        "bit_or",
        &[],
        IntrinsicCategory::Bitwise,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "compute a bitwise or once the bitwise intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(39),
        "bit_xor",
        &[],
        IntrinsicCategory::Bitwise,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "compute a bitwise xor once the bitwise intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(40),
        "shl",
        &[],
        IntrinsicCategory::Bitwise,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "shift a value left once the bitwise intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(41),
        "shr",
        &[],
        IntrinsicCategory::Bitwise,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "shift a value right once the bitwise intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(42),
        "rotl",
        &[],
        IntrinsicCategory::Bitwise,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "rotate bits left once the bitwise intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(43),
        "rotr",
        &[],
        IntrinsicCategory::Bitwise,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "rotate bits right once the bitwise intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(44),
        "pop_count",
        &[],
        IntrinsicCategory::Bitwise,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "count set bits once the bitwise intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(45),
        "clz",
        &[],
        IntrinsicCategory::Bitwise,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "count leading zero bits once the bitwise intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(46),
        "ctz",
        &[],
        IntrinsicCategory::Bitwise,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "count trailing zero bits once the bitwise intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(47),
        "byte_swap",
        &[],
        IntrinsicCategory::Bitwise,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "swap byte order once the bitwise intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(48),
        "bit_reverse",
        &[],
        IntrinsicCategory::Bitwise,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(1),
        IntrinsicLoweringMode::Deferred,
        "reverse bit order once the bitwise intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(49),
        "checked_add",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "perform checked addition once the overflow intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(50),
        "checked_sub",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "perform checked subtraction once the overflow intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(51),
        "wrapping_add",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "perform wrapping addition once the overflow intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(52),
        "wrapping_sub",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "perform wrapping subtraction once the overflow intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(53),
        "saturating_add",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "perform saturating addition once the overflow intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(54),
        "saturating_sub",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "perform saturating subtraction once the overflow intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(55),
        "overflowing_add",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "perform overflowing addition once the overflow intrinsic contract is frozen",
    ),
    IntrinsicEntry::new(
        IntrinsicId::new(56),
        "overflowing_sub",
        &[],
        IntrinsicCategory::Arithmetic,
        IntrinsicSurface::DotRootCall,
        IntrinsicAvailability::V1,
        IntrinsicStatus::Unsupported,
        IntrinsicArity::Exactly(2),
        IntrinsicLoweringMode::Deferred,
        "perform overflowing subtraction once the overflow intrinsic contract is frozen",
    ),
];

pub const fn intrinsic_registry() -> &'static [IntrinsicEntry] {
    INTRINSICS
}

pub const fn all_intrinsics() -> &'static [IntrinsicEntry] {
    intrinsic_registry()
}

pub fn intrinsic_by_canonical_name(name: &str) -> Option<&'static IntrinsicEntry> {
    intrinsic_registry().iter().find(|entry| entry.name == name)
}

pub fn intrinsic_by_alias(alias: &str) -> Option<&'static IntrinsicEntry> {
    intrinsic_registry()
        .iter()
        .find(|entry| entry.aliases.contains(&alias))
}

pub fn intrinsics_for_surface(surface: IntrinsicSurface) -> Vec<&'static IntrinsicEntry> {
    intrinsic_registry()
        .iter()
        .filter(|entry| entry.surface == surface)
        .collect()
}

pub fn intrinsic_by_id(id: IntrinsicId) -> Option<&'static IntrinsicEntry> {
    intrinsic_registry().iter().find(|entry| entry.id == id)
}

pub fn reserved_intrinsic_for_surface(
    surface: IntrinsicSurface,
    name: &str,
) -> Option<&'static IntrinsicEntry> {
    intrinsic_registry().iter().find(|entry| {
        entry.surface == surface
            && (entry.name == name || entry.aliases.iter().any(|alias| *alias == name))
    })
}

pub fn is_reserved_intrinsic_name_for_surface(surface: IntrinsicSurface, name: &str) -> bool {
    reserved_intrinsic_for_surface(surface, name).is_some()
}

pub fn lowering_mode_for_intrinsic(id: IntrinsicId) -> Option<IntrinsicLoweringMode> {
    intrinsic_by_id(id).map(|entry| entry.lowering_mode)
}

pub fn roadmap_for_intrinsic(id: IntrinsicId) -> Option<IntrinsicRoadmap> {
    intrinsic_by_id(id).map(|entry| match entry.id.index() {
        0..=8 | 12 | 13 => IntrinsicRoadmap::CurrentV1,
        9 | 10 | 11 | 14 | 15 | 21 | 22 => IntrinsicRoadmap::LikelyV1x,
        16..=20 => IntrinsicRoadmap::V3,
        23..=36 => IntrinsicRoadmap::CoreStdInstead,
        37..=56 => IntrinsicRoadmap::V2,
        _ => IntrinsicRoadmap::V2,
    })
}

pub fn intrinsics_for_roadmap(roadmap: IntrinsicRoadmap) -> Vec<&'static IntrinsicEntry> {
    intrinsic_registry()
        .iter()
        .filter(|entry| roadmap_for_intrinsic(entry.id) == Some(roadmap))
        .collect()
}

pub fn intrinsics_for_lowering_mode(
    lowering_mode: IntrinsicLoweringMode,
) -> Vec<&'static IntrinsicEntry> {
    intrinsic_registry()
        .iter()
        .filter(|entry| entry.lowering_mode == lowering_mode)
        .collect()
}
