use colored::Colorize;
use std::fmt;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum BUILDIN {
    ANY,
    Use,
    Def,
    Seg,
    Var,
    Log,
    Con,
    Fun,
    Pro,
    Typ,
    Std,
    Ali,
    Imp,
    Lab,

    Not,
    Or,
    Xor,
    Nor,
    And,
    Nand,
    As,
    Cast,
    If,
    Else,
    When,
    While,
    Loop,
    Is,
    At,
    Has,
    In,
    On,
    Case,
    This,
    Selfi,
    Break,
    Return,
    Yeild,
    Panic,
    Report,
    Check,
    Assert,
    Where,
    True,
    False,
    Each,
    For,
    Do,
    Go,
    Get,
    Of,
    Let,
}

impl fmt::Display for BUILDIN {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let t = match self {
            BUILDIN::Use => Some("use"),
            BUILDIN::Var => Some("var"),
            BUILDIN::Log => Some("log"),
            BUILDIN::Con => Some("con"),
            BUILDIN::Def => Some("def"),
            BUILDIN::Seg => Some("seg"),
            BUILDIN::Fun => Some("fun"),
            BUILDIN::Pro => Some("pro"),
            BUILDIN::Typ => Some("typ"),
            BUILDIN::Std => Some("std"),
            BUILDIN::Ali => Some("ali"),
            BUILDIN::Imp => Some("imp"),
            BUILDIN::Lab => Some("lab"),
            BUILDIN::Not => Some("not"),
            BUILDIN::Or => Some("or"),
            BUILDIN::Xor => Some("xor"),
            BUILDIN::Nor => Some("nor"),
            BUILDIN::And => Some("and"),
            BUILDIN::Nand => Some("nand"),
            BUILDIN::As => Some("as"),
            BUILDIN::Cast => Some("cast"),
            BUILDIN::If => Some("if"),
            BUILDIN::Else => Some("else"),
            BUILDIN::While => Some("while"),
            BUILDIN::Of => Some("of"),
            BUILDIN::When => Some("when"),
            BUILDIN::Loop => Some("loop"),
            BUILDIN::Is => Some("is"),
            BUILDIN::Has => Some("has"),
            BUILDIN::In => Some("in"),
            BUILDIN::On => Some("on"),
            BUILDIN::At => Some("at"),
            BUILDIN::Case => Some("case"),
            BUILDIN::This => Some("this"),
            BUILDIN::Selfi => Some("self"),
            BUILDIN::Break => Some("break"),
            BUILDIN::Return => Some("return"),
            BUILDIN::Yeild => Some("yeild"),
            BUILDIN::Panic => Some("panic"),
            BUILDIN::Report => Some("report"),
            BUILDIN::Check => Some("check"),
            BUILDIN::Assert => Some("assert"),
            BUILDIN::Where => Some("where"),
            BUILDIN::True => Some("true"),
            BUILDIN::False => Some("false"),
            BUILDIN::Each => Some("each"),
            BUILDIN::For => Some("for"),
            BUILDIN::Do => Some("do"),
            BUILDIN::Go => Some("go"),
            BUILDIN::Get => Some("get"),
            BUILDIN::Let => Some("let"),
            _ => None,
        };
        write!(
            f,
            "{}{}",
            " BUILDIN  ".black().on_red(),
            match t {
                Some(val) => {
                    (":".to_string().white().on_black().to_string() + &format!(" {} ", val))
                        .black()
                        .on_red()
                        .to_string()
                }
                None => "".to_string(),
            },
        )
    }
}
