[package]
name = "getset"
version = "0.1.0"
authors = ["Trim Bresilla <trim.bresilla@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro=true
[dependencies]
quote="^0.3.12"
syn="^0.11.4"
