name: C/C++ CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: packges
      run: sudo apt install -y libcurl3 g++7 cppcheck iwyu valgrind clang-tidy-6.0 libclang-6.0-dev libboost-all-dev
    - name: kcov
      run: wget https://github.com/SimonKagstrom/kcov/archive/v36.tar.gz && tar xzf v36.tar.gz && cd kcov-36 && mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.kcov -DCMAKE_BUILD_TYPE=Release && make -j2 &&  make install
    - name: cmake
      run: cmake -H. -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=FastDebug
    - name: make
      run: cmake --build build/ --target
    - name: test
      run: cd build && ctest
